name: Build and deploy spring app
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and deploy springBoot
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4.1.4
     - name: setup jdk 17
       uses: actions/setup-java@v3
       with:
         distribution: 'corretto'
         java-version: 17

     - name: Unit tests
       run: mvn -B test --file pom.xml
     - name: Build the application
       run:
         mvn clean
         mvn -B package --file pom.xml

